version: "3"

services:
  php:
    build:
      context: .
      dockerfile: ./_/php/Dockerfile
    volumes:
      - ./server:/var/www
      - ./server/.env.example:/var/www/.env
    ports:
      - 80:80
    command: bash -c "
      composer install
      && php artisan key:generate
      && php artisan serv --host=0.0.0.0 --port=80"

  nginx:
    build:
      context: .
      dockerfile: ./_/nginx/Dockerfile
    working_dir: /var/www
    volumes:
      - ./server:/var/www
      - ./_/nginx/default.conf:/etc/nginx/conf.d/default.conf

  db:
    build:
      context: .
      dockerfile: ./_/db/Dockerfile
    environment:
      MYSQL_DATABASE: b_twitter_laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: docker
      TZ: "Asia/Tokyo"
    volumes:
      - data:/var/lib/mysql:cached
      - ./_/db/initdb.d:/docker-entrypoint-initdb.d
    tty: true
    ports:
      - 3306:3306

volumes:
  data:
    driver: local
