version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: ./_/nginx/Dockerfile
    volumes:
      - app-volume:/var/www
      - ./_/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

  php:
    build:
      context: .
      dockerfile: ./_/php/Dockerfile
    volumes:
      - app-volume:/var/www
      - ./server/.env.example:/var/www/.env
    ports:
      - 9000:9000

  db:
    build:
      context: .
      dockerfile: ./_/db/Dockerfile
    environment:
      MYSQL_DATABASE: laravel_twitter_clone
      MYSQL_USER: root
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: docker
      TZ: "Asia/Tokyo"
    volumes:
      - data:/var/lib/mysql:cached
      - ./_/db/initdb.d:/docker-entrypoint-initdb.d
    tty: true
    ports:
      - 3306:3306

volumes:
  app-volume:
  data:
    driver: local
