version: "3"

services:
  php:
    build: ./_/php
    volumes:
      - ./server:/var/www
    ports:
      - 80:80
    # command: php artisan serv --host=0.0.0.0 --port=80

  nginx:
    image: nginx:1.18-alpine
    working_dir: /var/www
    volumes:
      - ./server:/var/www
      - ./_/nginx/default.conf:/etc/nginx/conf.d/default.conf

  db:
    build: ./_/db
    environment:
      MYSQL_DATABASE: b_twitter_laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: docker
      TZ: "Asia/Tokyo"
    volumes:
      - data:/var/lib/mysql:cached
    tty: true
    command: --innodb-use-native-aio=0
    ports:
      - 3306:3306

volumes:
  data:
    driver: local
